# <!-- Powered by BMAD™ Core -->
name: bmad-wechat-mini-game-dev
version: 1.0.0
short-title: WeChat Mini Game Dev Pack
description: >-
  WeChat Mini Game Development expansion pack for BMad Method
author: Jules
slashPrefix: madmad
